---
- name: "[PRIMARY]: Configure Gravity-Sync Primary"
  block:
    - name: "[PRIMARY]: Run initial Primary Configuration Check"
      shell: |
        export GS_INSTALL=primary
        curl -sSL https://gravity.vmstan.com | bash

    # - name: "[PRIMARY]: Deploy Public SSH key"
    #   copy:
    #     src: "files/pihole-ssh-public.key"
    #     # content: "{{ pihole_ssh_public_key }}"
    #     dest: "/home/{{ ansible_user }}/.ssh/pihole-gravity.pub"
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
    #     mode: 0644
    #     decrypt: yes
    #     force: yes


    # - name: "[PRIMARY]: Register ssh key"
    #   shell: cat /home/{{ ansible_user }}/.ssh/pihole-gravity.pub
    #   register: public_ssh_key
    #   changed_when: false

    - name: "[PRIMARY]: Authorize Public SSH key"
      authorized_key:
        user: "{{ ansible_user }}"
        key: '{{ item }}'
        state: present
      with_file: "files/pihole-ssh-public.key"

