---
- name: Ensure PiVPN folder exists
  file:
    path: /etc/pivpn
    state: directory
  
- name: Copy PiVPN setup config file
  copy:
    src: setupVars.conf
    dest: /etc/pivpn/setupVars.conf

- name: Download PiVPN Install script
  get_url:
    url: https://install.pivpn.io
    dest: /tmp/pivpn-install.sh
  
- name: Ensure PiVPN Install script is executable
  file:
    path: /tmp/pivpn-install.sh
    state: file
    mode: '0755'

- name: Run PiVPN Install script
  command: /tmp/pivpn-install.sh

- name: Remove PiVPN Install script
  file:
    path: /tmp/pivpn-install.sh
    state: absent