---
- name: Install glances Prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3
    - python3-pip

- name: Install Bottle
  pip:
    name: bottle
    state: latest

- name: Install Glances
  pip:
    name: glances
    state: latest

