---
- name: "flux: Restart Watchdog"
  shell: bash -ilc 'pm2 reload watchdog --watch'
  become: true
  become_user: "{{ ansible_user }}"

- name: Restart pm2
  systemd:
    name: pm2-{{ ansible_user }}.service
    state: restarted
  become: true

