---
- name: Update APT packages
  apt:
    update_cache: true
  become: true

- name: Upgrade APT packages
  apt:
    upgrade: 'yes' # <-- This expects a STRING for some reason...
  become: true

- name: Install APT packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  become: true
  loop: "{{ commonPackages }}"

- name: Check for pending reboot
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  changed_when: false

- name: REBOOT REQUIRED - IF THIS IS YELLOW THIS NODE NEEDS TO REBOOT
  ansible.builtin.command: echo "This needs to reboot"
  when: reboot_required.stat.exists
