---
- name: Install Nala
  block:
    - name: Add nala repo gpg key
      apt_key:
        url: "https://deb.volian.org/volian/scar.key"
        state: present

    - name: Add nala repository source
      apt_repository:
        repo: "deb https://deb.volian.org/volian/ scar main"
        state: present

    - name: Install Nala
      apt:
        name: nala
        state: latest
      when: ansible_distribution_major_version == "22"

    - name: Install Nala-legacy
      apt:
        name: nala-legacy
        state: latest
        update_cache: yes
      when: ansible_distribution_major_version == "20"
  become: true
