---
- name: Update APT
  ansible.builtin.import_tasks:
    file: common-updateOS.yml
  tags:
    - common
    - update
    - updateOS
    - never

- name: Rebooting if needed
  ansible.builtin.import_tasks:
    file: common-reboot.yml
  when:
    - reboot_required is defined
    - reboot_required.stat.exists
  tags:
    - reboot

- name: Deploy update alias
  copy:
    src: "update_alias.sh"
    dest: /etc/profile.d/update_alias.sh
    mode: 0644
    force: true
  become: true
  tags:
    - common
    - never

- name: Install Common APT Packages
  ansible.builtin.import_tasks:
    file: common-packages.yml
  tags:
    - common
    - packages
    - common-packages
    - never

- import_tasks: unattended-upgrades.yml
  tags:
    - common
    - unattended-upgrades
    - never
