---
flux:
  gateway: '192.168.1.1'
  # Setting a default eps value. Provide one in fluxnodes if it differs
  default_eps: 90
  nodes:
    pm-flux-nimbus-0:
      eps: 180
      upnp_port: '16127'
      collid: 'b94a97ffb5d030a1c8cd66b9f43c7d17911fe7ad435b85657d61894dba8ddf32'
      tier: 'Nimbus'
      proxmox_vm_id: 120
