---
- hosts: all,!proxmox # <-- Apply to all hosts except the proxmox host group.
  vars:
    roles_path: /etc/ansible/roles:../roles
    inventory: ../hosts.ini
  become: yes

  roles:
    - { role: common, tags: common }
