---
- hosts: proxmox
  vars:
    roles_path: /etc/ansible/roles:../roles
    inventory: ../hosts.ini

  roles:
    - { role: common, tags: common }
    - { role: proxmox, tags: proxmox }
    - { role: glances, tags: glances }
