---
- name: Install Prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: "Docker: Ensure portainer directory exists"
  file:
    path: "{{ portainer_docker_home }}"
    state: directory
    mode: 0755
    force: true
  become: yes

- name: "Docker: Ensure portainer data directory exists"
  file:
    path: "{{ portainer_docker_home }}/data"
    state: directory
    mode: 0755
    force: true
  become: yes

- name: Start portainer Docker Image
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    published_ports:
      - "{{ portainer_host_port }}:{{ portainer_docker_port }}"
    volumes:
      - "{{ portainer_docker_home }}/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: "unless-stopped"
    force_kill: yes
    pull: yes
    detach: true
    pid_mode: host
  become: yes

- name: Enable docker on bootup
  shell: systemctl enable docker
