---

- name: Checking for fluxbench file
  stat:
    path: "/home/{{ ansible_user }}/.fluxbenchmark/fluxbench.conf"
  register: fluxbench
  tags: config

- name: Deploy fluxbench config file
  template:
    src: "fluxbench.j2"
    dest: "/home/{{ ansible_user }}/.fluxbenchmark/fluxbench.conf"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when: fluxbench.stat.exists
  tags: config

