---
- name: Loading secret vars...
  include_vars:
    file: secrets.yaml
  tags: config

- name: Create and Push Alias commands
  include: flux-PushAliases.yml
  tags:
    - flux-PushAliases
    - never

- name: Pull FluxOS updates from GitHub and install
  include: flux-UpdateFluxOS.yml
  tags:
      - fluxUpdate
      - never

- name: Create And Push Install Config Files for a Node/User
  include: flux-PushInstallConf.yml
  tags:
      - flux-PushInstallConf
      - never

- name: Run multitoolbox options to install and configure FluxOS
  include: flux-InstallFlux.yml
  tags:
    - flux-InstallFlux
    - never

- name: Create And Push Watchdog Config Files for a Node/User
  include: flux-PushWatchdogConf.yml
  tags:
      - flux-PushWatchdogConf
      - never

