---
- name: Install Flux Docker
  shell: |
    export usernew="{{ ansible_user }}"
    echo "1" | bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)
  become: true
  become_user: root
  args:
    executable: /bin/bash

# - name: "Installing FluxNode - Go get some coffee. :)"
#   shell: |
#     echo "2" | bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)
#   args:
#     executable: /bin/bash
#   # async: 28800 # 8 hours
#   become: true
#   become_user: "{{ ansible_user }}"
